# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{userstamps}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephan Kaag"]
  s.date = %q{2010-06-04}
  s.description = %q{Gem that extends ActiveRecord with stamping for created_by and updated_by fields}
  s.email = %q{stephan.kaag@holder.nl}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/active_record/associations/user_stamps.rb",
     "lib/userstamps.rb",
     "spec/.gitignore",
     "spec/spec_helper.rb",
     "spec/user_stamps_spec.rb",
     "userstamps.gemspec"
  ]
  s.homepage = %q{http://github.com/stephankaag/userstamps}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extending ActiveRecord with stamping for created_by and updated_by fields}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/user_stamps_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

